import { Product } from '@/types';

export const products: Product[] = [
    {
        id: '1',
        barcode: '1001',
        name: 'Fresh Red Apple',
        nameSi: 'නැවුම් රතු ඇපල්',
        nameTa: 'புதிய சிவப்பு ஆப்பிள்',
        price: 150.00,
        image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6bccb?q=80&w=2574&auto=format&fit=crop',
        category: 'Fruits'
    },
    {
        id: '2',
        barcode: '1002',
        name: 'Loaf of White Bread',
        nameSi: 'සුදු පාන් රාත්තලක්',
        nameTa: 'வெள்ளை ரொட்டி துண்டு',
        price: 180.00,
        image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=2672&auto=format&fit=crop',
        category: 'Bakery'
    },
    {
        id: '3',
        barcode: '1003',
        name: 'Amul Fresh Milk (1L)',
        nameSi: 'අමුල් නැවුම් කිරි (ලීටර් 1)',
        nameTa: 'அமுல் புதிய பால் (1L)',
        price: 450.00,
        image: 'https://images.unsplash.com/photo-1563636619-e9107d6adb20?q=80&w=2670&auto=format&fit=crop',
        category: 'Dairy'
    },
    {
        id: '4',
        barcode: '1004',
        name: 'Basmati Rice (1kg)',
        nameSi: 'බාස්මතී සහල් (කිලෝග්‍රෑම් 1)',
        nameTa: 'பாஸ்மதி அரிசி (1 கிலோ)',
        price: 650.00,
        image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?q=80&w=2670&auto=format&fit=crop',
        category: 'Grains'
    },
    {
        id: '5',
        barcode: '1005',
        name: 'Red Onions (500g)',
        nameSi: 'රතු ළුණු (ග්‍රෑම් 500)',
        nameTa: 'சிவப்பு வெங்காயம் (500 கிராம்)',
        price: 220.00,
        image: 'https://images.unsplash.com/photo-1508747703725-7197771375a0?q=80&w=2574&auto=format&fit=crop',
        category: 'Vegetables'
    },
    {
        id: '6',
        barcode: '1006',
        name: 'Classic Potato Chips',
        nameSi: 'ක්ලැසික් අල පෙති',
        nameTa: 'கிளாசிக் உருளைக்கிழங்கு சிப்ஸ்',
        price: 320.00,
        image: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?q=80&w=2670&auto=format&fit=crop',
        category: 'Snacks'
    },
    {
        id: '7',
        barcode: 'loose_01',
        name: 'Cavendish Banana',
        nameSi: 'කෙසෙල්',
        nameTa: 'வாழைப்பழம்',
        price: 45.00,
        image: 'https://images.unsplash.com/photo-1571771894821-ad990241fab7?q=80&w=2670&auto=format&fit=crop',
        category: 'Fruits'
    },
    {
        id: '8',
        barcode: 'loose_02',
        name: 'Sun-ripened Tomato',
        nameSi: 'තක්කාලි',
        nameTa: 'தக்காளி',
        price: 35.00,
        image: 'https://images.unsplash.com/photo-1518977676601-b53f02bad67b?q=80&w=2674&auto=format&fit=crop',
        category: 'Vegetables'
    },
    {
        id: '9',
        barcode: 'loose_03',
        name: 'Sweet Corn',
        nameSi: 'ඉරිඟු',
        nameTa: 'சோளம்',
        price: 85.00,
        image: 'https://images.unsplash.com/photo-1551754655-cd27e38d2076?q=80&w=2674&auto=format&fit=crop',
        category: 'Grains'
    }
];

export const members: { [id: string]: { name: string; points: number; discount: number } } = {
    'M001': { name: 'Asiri Perera', points: 1250, discount: 5 },
    'M002': { name: 'Kumar Sangakara', points: 3400, discount: 10 },
    'M003': { name: 'Thilina Rose', points: 450, discount: 2 }
};

export const translations = {
    EN: {
        welcome: 'Welcome to Supermarket',
        start: 'Start Scanning Items',
        scan_instruction: 'Scan product barcode',
        bagging_instruction: 'Place item in bagging area',
        proceed_to_payment: 'Proceed to payment',
        subtotal: 'Gross Total',
        tax: 'Tax (VAT 15%)',
        total: 'Payable Amount',
        pay_now: 'Authorize Payment',
        help: 'Staff Alert',
        remove: 'Discard',
        payment_success: 'Transaction Success',
        thank_you: 'Purchase complete. Visit again!',
        print_receipt: 'Print Receipt',
        finish: 'New Session',
        select_language: 'Language Selection',
        select_payment: 'Payment Terminal',
        card: 'Direct Card',
        qr: 'Mobile QR',
        cash: 'Manual Cash',
        processing: 'Verifying Security...',
        item_scanned: 'SKU Added',
        cart_empty: 'Cart is currently empty',
        back: 'Return',
        search: 'Search Item',
        lookup: 'Product Lookup',
        bags: 'Add Bags',
        bags_count: 'Bags Added',
        add: 'Add Item',
        loyalty: 'Member ID',
        member_welcome: 'Welcome Back, ',
        savings: 'Member Savings',
        discount: 'Promotion Applied',
        call_staff: 'Staff Notified',
        staff_desc: 'An attendant will assist you shortly.',
        confirm: 'Confirm Request'
    },
    SI: {
        welcome: 'සාදරයෙන් පිළිගනිමු',
        start: 'ස්කෑන් කිරීම ආරම්භ කරන්න',
        scan_instruction: 'බාර්කෝඩ් එක ඇතුලත් කරන්න',
        bagging_instruction: 'අයිතමය තබන්න',
        proceed_to_payment: 'ගෙවීම් වලට යන්න',
        subtotal: 'මුළු එකතුව',
        tax: 'බදු (VAT 15%)',
        total: 'ගෙවිය යුතු මුදල',
        pay_now: 'දැන් ගෙවන්න',
        help: 'සේවක සහය',
        remove: 'ඉවත් කරන්න',
        payment_success: 'ගෙවීම සාර්ථකයි',
        thank_you: 'ස්තුතියි! නැවත එන්න.',
        print_receipt: 'රසීදු පත',
        finish: 'අලුත් සිකුම්',
        select_language: 'භාෂාව',
        select_payment: 'ගෙවීමේ ක්‍රමය',
        card: 'කාඩ්පත්',
        qr: 'QR මගින්',
        cash: 'මුදල් මගින්',
        processing: 'කරුණාකර රැඳී සිටින්න...',
        item_scanned: 'ඇතුලත් කරන ලදී',
        cart_empty: 'කරත්තය හිස්ය',
        back: 'ආපසු',
        search: 'සොයන්න',
        lookup: 'භාණ්ඩය තෝරන්න',
        bags: 'බෑග් එකතු කරන්න',
        bags_count: 'බෑග් ගණන',
        add: 'එකතු කරන්න',
        loyalty: 'සාමාජික අංකය',
        member_welcome: 'ආයුබෝවන්, ',
        savings: 'සාමාජික ඉතිරිය',
        discount: 'වට්ටම්',
        call_staff: 'සහය ඉල්ලා ඇත',
        staff_desc: 'සේවකයෙකු පැමිණෙනු ඇත.',
        confirm: 'තහවුරු කරන්න'
    },
    TA: {
        welcome: 'வரவேற்கிறோம்',
        start: 'தொடங்குங்கள்',
        scan_instruction: 'பார்கோடை ஸ்கேன் செய்யுங்கள்',
        bagging_instruction: 'பொருளை வைக்கவும்',
        proceed_to_payment: 'பணம் செலுத்தவும்',
        subtotal: 'மொத்த தொகை',
        tax: 'வரி (VAT 15%)',
        total: 'செலுத்த வேண்டிய தொகை',
        pay_now: 'செலுத்துங்கள்',
        help: 'உதவி',
        remove: 'அகற்று',
        payment_success: 'வெற்றி',
        thank_you: 'நன்றி! மீண்டும் வருக.',
        print_receipt: 'ரசீது',
        finish: 'புதிய அமர்வு',
        select_language: 'மொழி',
        select_payment: 'முறை',
        card: 'அட்டை',
        qr: 'QR முறை',
        cash: 'பணம்',
        processing: 'செயலாக்கப்படுகிறது...',
        item_scanned: 'பொருள் சேர்க்கப்பட்டது',
        cart_empty: 'வண்டி காலியாக உள்ளது',
        back: 'பின்னால்',
        search: 'தேடுங்கள்',
        lookup: 'பொருட்களை தேடுங்கள்',
        bags: 'பைகளைச் சேர்க்கவும்',
        bags_count: 'சேர்க்கப்பட்ட பைகள்',
        add: 'சேர்க்கவும்',
        loyalty: 'உறுப்பினர் ID',
        member_welcome: 'வணக்கம், ',
        savings: 'உறுப்பினர் சேமிப்பு',
        discount: 'தள்ளுபடி',
        call_staff: 'ஊழியர் அறியப்பட்டது',
        staff_desc: 'உதவி விரைவில் வரும்.',
        confirm: 'உறுதிப்படுத்துக'
    }
};
